#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pkcs11-helper
Version  : 1.22
Release  : 1
URL      : https://github.com/OpenSC/pkcs11-helper/releases/download/pkcs11-helper-1.22/pkcs11-helper-1.22.tar.bz2
Source0  : https://github.com/OpenSC/pkcs11-helper/releases/download/pkcs11-helper-1.22/pkcs11-helper-1.22.tar.bz2
Summary  : PKCS#11 helper library
Group    : Development/Tools
License  : GPL-2.0
Requires: pkcs11-helper-lib
Requires: pkcs11-helper-doc
BuildRequires : openssl-dev
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(openssl)

%description
The pkcs11-helper library allows using multiple PKCS#11 providers at
the same  time, selecting keys by id, label or certificate subject,
handling  card removal and card insert events, handling card re-insert
to a  different slot, supporting session expiration serialization and
much more, all using a simple API.

%package dev
Summary: dev components for the pkcs11-helper package.
Group: Development
Requires: pkcs11-helper-lib
Provides: pkcs11-helper-devel

%description dev
dev components for the pkcs11-helper package.


%package doc
Summary: doc components for the pkcs11-helper package.
Group: Documentation

%description doc
doc components for the pkcs11-helper package.


%package lib
Summary: lib components for the pkcs11-helper package.
Group: Libraries

%description lib
lib components for the pkcs11-helper package.


%prep
%setup -q -n pkcs11-helper-1.22

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1496170755
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1496170755
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pkcs11-helper-1.0/pkcs11.h
/usr/include/pkcs11-helper-1.0/pkcs11h-certificate.h
/usr/include/pkcs11-helper-1.0/pkcs11h-core.h
/usr/include/pkcs11-helper-1.0/pkcs11h-data.h
/usr/include/pkcs11-helper-1.0/pkcs11h-def.h
/usr/include/pkcs11-helper-1.0/pkcs11h-engines.h
/usr/include/pkcs11-helper-1.0/pkcs11h-openssl.h
/usr/include/pkcs11-helper-1.0/pkcs11h-token.h
/usr/include/pkcs11-helper-1.0/pkcs11h-version.h
/usr/lib64/libpkcs11-helper.so
/usr/lib64/pkgconfig/libpkcs11-helper-1.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/pkcs11\-helper/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpkcs11-helper.so.1
/usr/lib64/libpkcs11-helper.so.1.0.0
