#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pkcs11-helper
Version  : 1.25.1
Release  : 6
URL      : https://github.com/OpenSC/pkcs11-helper/releases/download/pkcs11-helper-1.25.1/pkcs11-helper-1.25.1.tar.bz2
Source0  : https://github.com/OpenSC/pkcs11-helper/releases/download/pkcs11-helper-1.25.1/pkcs11-helper-1.25.1.tar.bz2
Summary  : PKCS#11 helper library
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: pkcs11-helper-lib = %{version}-%{release}
Requires: pkcs11-helper-license = %{version}-%{release}
Requires: pkcs11-helper-man = %{version}-%{release}
BuildRequires : openssl-dev
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(openssl)

%description
The pkcs11-helper library allows using multiple PKCS#11 providers at
the same  time, selecting keys by id, label or certificate subject,
handling  card removal and card insert events, handling card re-insert
to a  different slot, supporting session expiration serialization and
much more, all using a simple API.

%package dev
Summary: dev components for the pkcs11-helper package.
Group: Development
Requires: pkcs11-helper-lib = %{version}-%{release}
Provides: pkcs11-helper-devel = %{version}-%{release}

%description dev
dev components for the pkcs11-helper package.


%package doc
Summary: doc components for the pkcs11-helper package.
Group: Documentation
Requires: pkcs11-helper-man = %{version}-%{release}

%description doc
doc components for the pkcs11-helper package.


%package lib
Summary: lib components for the pkcs11-helper package.
Group: Libraries
Requires: pkcs11-helper-license = %{version}-%{release}

%description lib
lib components for the pkcs11-helper package.


%package license
Summary: license components for the pkcs11-helper package.
Group: Default

%description license
license components for the pkcs11-helper package.


%package man
Summary: man components for the pkcs11-helper package.
Group: Default

%description man
man components for the pkcs11-helper package.


%prep
%setup -q -n pkcs11-helper-1.25.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1542707752
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1542707752
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pkcs11-helper
cp COPYING %{buildroot}/usr/share/package-licenses/pkcs11-helper/COPYING
cp COPYING.BSD %{buildroot}/usr/share/package-licenses/pkcs11-helper/COPYING.BSD
cp COPYING.GPL %{buildroot}/usr/share/package-licenses/pkcs11-helper/COPYING.GPL
cp distro/debian/copyright %{buildroot}/usr/share/package-licenses/pkcs11-helper/distro_debian_copyright
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pkcs11-helper-1.0/pkcs11.h
/usr/include/pkcs11-helper-1.0/pkcs11h-certificate.h
/usr/include/pkcs11-helper-1.0/pkcs11h-core.h
/usr/include/pkcs11-helper-1.0/pkcs11h-data.h
/usr/include/pkcs11-helper-1.0/pkcs11h-def.h
/usr/include/pkcs11-helper-1.0/pkcs11h-engines.h
/usr/include/pkcs11-helper-1.0/pkcs11h-openssl.h
/usr/include/pkcs11-helper-1.0/pkcs11h-token.h
/usr/include/pkcs11-helper-1.0/pkcs11h-version.h
/usr/lib64/libpkcs11-helper.so
/usr/lib64/pkgconfig/libpkcs11-helper-1.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/pkcs11\-helper/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpkcs11-helper.so.1
/usr/lib64/libpkcs11-helper.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pkcs11-helper/COPYING
/usr/share/package-licenses/pkcs11-helper/COPYING.BSD
/usr/share/package-licenses/pkcs11-helper/COPYING.GPL
/usr/share/package-licenses/pkcs11-helper/distro_debian_copyright

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/pkcs11-helper-1.8
